START TRANSACTION;

DELETE FROM push_logs;
DELETE FROM conversations;
DELETE FROM conv_state;
DELETE FROM memories;
DELETE FROM schedules;
DELETE FROM memos;
DELETE FROM tasks;

ALTER TABLE push_logs AUTO_INCREMENT = 1;
ALTER TABLE conversations AUTO_INCREMENT = 1;
ALTER TABLE conv_state AUTO_INCREMENT = 1;
ALTER TABLE memories AUTO_INCREMENT = 1;
ALTER TABLE schedules AUTO_INCREMENT = 1;
ALTER TABLE memos AUTO_INCREMENT = 1;
ALTER TABLE tasks AUTO_INCREMENT = 1;

COMMIT;