SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE push_logs;
TRUNCATE TABLE conversations;
TRUNCATE TABLE conv_state;
TRUNCATE TABLE memories;
TRUNCATE TABLE schedules;
TRUNCATE TABLE memos;
TRUNCATE TABLE tasks;
TRUNCATE TABLE users;

SET FOREIGN_KEY_CHECKS = 1;